[build]
  command = "npm run build"
  publish = "dist"
  base = "/"

[dev]
  command = "npm run dev"
  port = 8080
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = {Role = "admin"}

# Cache control for static assets with hashed filenames
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache control for index.html and other HTML files
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Pragma = "no-cache"
    Expires = "0"
